const faqDatabase = [
  {
    id: 1,
    question: "What is Spylt Milk?",
    answer: "Spylt Milk is a premium protein-fortified dairy beverage designed for milk lovers and active lifestyles. It combines real milk with balanced nutrition, a smooth texture, and flavors like Chocolate, Vanilla, Strawberry, and more.",
    tags: ["spylt", "milk", "product", "overview", "what is"],
    aliases: ["what is spylt", "spylt drink", "spylt milk product", "spylt dairy beverage"],
  },
  {
    id: 2,
    question: "How much protein is in Spylt Milk?",
    answer: "Spylt Milk delivers a strong protein boost with around 20–24g of protein per bottle, depending on the flavor. It’s built to support muscle recovery and daily protein goals without compromising taste.",
    tags: ["protein", "macros", "nutrition", "spylt"],
    aliases: ["spylt protein", "protein in spylt", "how much protein", "protien in spylt"],
  },
  {
    id: 3,
    question: "Which Spylt flavor has the most protein?",
    answer: "Max Chocolate is the top protein pick in the Spylt lineup. It typically contains the highest protein per serving while keeping the taste rich and satisfying.",
    tags: ["best flavor", "protein", "max chocolate", "spylt"],
    aliases: ["most protein flavor", "flavor with most protein", "max choc protein", "best protein spylt"],
  },
  {
    id: 4,
    question: "Is Spylt Milk healthy?",
    answer: "Yes, Spylt Milk is crafted to be a healthy dairy option with real milk, protein, vitamins, and balanced ingredients. It supports recovery, daily nutrition, and active lifestyles when enjoyed as part of a balanced diet.",
    tags: ["healthy", "nutrition", "health benefits", "spylt"],
    aliases: ["spylt healthy", "good for you", "healthy milk", "is spylt healthy"],
  },
  {
    id: 5,
    question: "What ingredients are used in Spylt Milk?",
    answer: "Spylt Milk uses real milk, milk proteins, natural flavors, vitamins, minerals, and minimal preservatives. The formula focuses on clean dairy nutrition with ingredients chosen for taste and muscle support.",
    tags: ["ingredients", "label", "what's inside", "spylt"],
    aliases: ["spylt ingredients", "what is in spylt", "what ingredients", "milk ingredients"],
  },
  {
    id: 6,
    question: "Does Spylt Milk contain sugar?",
    answer: "Some Spylt flavors contain natural sugar from milk and added sweeteners, while others are formulated to be lower sugar. Check the flavor label for exact sugar content, especially if you want a lighter, low-sugar option.",
    tags: ["sugar", "sweet", "nutrition", "spylt"],
    aliases: ["spylt sugar", "sugar in spylt", "low sugar spylt", "sugar content"],
  },
  {
    id: 7,
    question: "How many calories are in Chocolate Spylt Milk?",
    answer: "Chocolate Spylt Milk usually has around 220–260 calories per bottle, depending on the recipe. It balances flavor and energy, making it a satisfying option for recovery and snack time.",
    tags: ["calories", "energy", "chocolate", "spylt"],
    aliases: ["cal in choc milk", "chocolate spylt calories", "calories in spylt chocolate", "calorie count"],
  },
  {
    id: 8,
    question: "Is Spylt Milk good after workouts?",
    answer: "Yes, Spylt Milk is ideal after workouts because it delivers high-quality protein, hydration, and muscle support. Its dairy nutrition helps recovery without feeling heavy.",
    tags: ["workout", "recovery", "protein", "spylt"],
    aliases: ["post workout milk", "recovery milk", "gym drink", "after exercise"],
  },
  {
    id: 9,
    question: "Can kids drink Spylt Milk?",
    answer: "Yes, kids can enjoy Spylt Milk as a tasty dairy option, especially when they need extra protein and nutrients. It’s best used as part of a healthy diet and not as a complete meal replacement.",
    tags: ["kids", "family", "safe", "spylt"],
    aliases: ["kid safe milk", "kids spylt", "milk for kids", "children drink"],
  },
  {
    id: 10,
    question: "What flavors does Spylt Milk offer?",
    answer: "Spylt Milk offers premium flavors like Max Chocolate, Vanilla Cream, Strawberry Cream, Cookies & Cream, and Peanut Butter Chocolate. Each flavor blends dairy nutrition with a smooth, satisfying taste.",
    tags: ["flavors", "variety", "options", "spylt"],
    aliases: ["spylt flavors", "what flavors", "best flavor", "flavor list"],
  },
  {
    id: 11,
    question: "Is Spylt Milk lactose free?",
    answer: "Most Spylt Milk variants are made from real milk and are not lactose-free. If you have lactose sensitivity, choose a specially labeled product or consult the packaging for lactose information.",
    tags: ["lactose", "diet", "allergy", "spylt"],
    aliases: ["lactose free spylt", "lactose in spylt", "is spylt lactose free", "milk lactose"],
  },
  {
    id: 12,
    question: "Does Spylt Milk contain caffeine?",
    answer: "No, Spylt Milk does not contain caffeine in the standard flavor range. Its focus is on protein, dairy nutrition, and flavor rather than energy stimulants.",
    tags: ["caffeine", "energy", "stimulant", "spylt"],
    aliases: ["spylt caffeine", "caffeine in milk", "contains caffeine", "coffee milk"],
  },
  {
    id: 13,
    question: "Which Spylt flavor tastes the best?",
    answer: "Taste is personal, but Max Chocolate is a crowd favorite for its rich, indulgent flavor. Vanilla Cream and Strawberry Cream are also top picks when you want a smoother, classic milk taste.",
    tags: ["best flavor", "taste", "popular", "spylt"],
    aliases: ["best spylt flavor", "tastes the best", "top flavor", "favorite flavor"],
  },
  {
    id: 14,
    question: "What vitamins are in Spylt Milk?",
    answer: "Spylt Milk includes vitamins like D and B12, along with mineral support such as calcium. It is formulated to add nutritional value beyond basic dairy.",
    tags: ["vitamins", "nutrition", "d vitamin", "spylt"],
    aliases: ["vitamins in spylt", "vitamin d spylt", "b12 in spylt", "milk vitamins"],
  },
  {
    id: 15,
    question: "Is Spylt Milk made from real milk?",
    answer: "Yes, Spylt Milk is made from real dairy milk with added protein, vitamins, and flavor. It is built to feel like premium milk while offering extra nutrition.",
    tags: ["real milk", "dairy", "authentic", "spylt"],
    aliases: ["real milk spylt", "made from milk", "dairy milk", "real dairy"],
  },
  {
    id: 16,
    question: "How much fat is in Spylt Milk?",
    answer: "Spylt Milk generally contains moderate fat levels to keep the texture rich without being heavy. Fat content varies by flavor, so check the label for exact grams per bottle.",
    tags: ["fat", "macros", "nutrition", "spylt"],
    aliases: ["fat in spylt", "spylt fat", "how much fat", "fat content"],
  },
  {
    id: 17,
    question: "Does Spylt Milk help build muscle?",
    answer: "Yes, Spylt Milk helps muscle building by supplying quality dairy protein and essential amino acids. It’s a smart choice after workouts or as a protein-rich snack.",
    tags: ["muscle", "build muscle", "recovery", "spylt"],
    aliases: ["muscle milk", "build muscle spylt", "gym protein", "protein for muscles"],
  },
  {
    id: 18,
    question: "Is Spylt Milk better than regular chocolate milk?",
    answer: "Spylt Milk is typically better than regular chocolate milk when you want added protein, vitamins, and nutrition. It’s designed for active use, while regular chocolate milk focuses mainly on taste.",
    tags: ["comparison", "regular milk", "chocolate milk", "spylt"],
    aliases: ["better than choc milk", "vs chocolate milk", "regular vs spylt", "chocolate milk comparison"],
  },
  {
    id: 19,
    question: "What is the shelf life of Spylt Milk?",
    answer: "Spylt Milk should be stored refrigerated and consumed by the date on the package. Typical shelf life is several weeks when kept cold and unopened.",
    tags: ["shelf life", "storage", "refrigeration", "spylt"],
    aliases: ["expiration", "shelf life spylt", "how long lasts", "storage life"],
  },
  {
    id: 20,
    question: "Can I drink Spylt Milk every day?",
    answer: "Yes, Spylt Milk can be enjoyed daily as part of a balanced diet. It offers protein, dairy nutrients, and flavor, but it should complement a healthy eating plan.",
    tags: ["daily", "every day", "habit", "spylt"],
    aliases: ["daily spylt", "drink every day", "everyday milk", "daily milk"],
  },
  {
    id: 21,
    question: "Does Spylt Milk contain artificial flavors?",
    answer: "Spylt Milk uses flavorings that create a premium taste, and some varieties may include natural and artificial flavor blends. For the cleanest option, check the ingredient label.",
    tags: ["artificial flavors", "clean label", "ingredients", "spylt"],
    aliases: ["artificial flavor spylt", "fake flavors", "natural flavors", "contains artificial flavors"],
  },
  {
    id: 22,
    question: "Which Spylt flavor has the least sugar?",
    answer: "The lower-sugar Spylt flavors are typically the lighter options like Vanilla Cream or a specially labeled low-sugar version. Check the nutrition panel for the lowest sugar per bottle.",
    tags: ["low sugar", "least sugar", "flavor", "spylt"],
    aliases: ["least sugar flavor", "low sugar spylt", "which flavor least sugar", "sugar free"],
  },
  {
    id: 23,
    question: "Is vanilla Spylt Milk healthy?",
    answer: "Vanilla Spylt Milk is a healthy choice that combines real dairy, protein, and balanced sweetness. It is a lighter flavor profile that still supports nutrition and recovery.",
    tags: ["vanilla", "healthy", "spylt"],
    aliases: ["vanilla spylt healthy", "healthy vanilla", "vanilla milk health", "is vanilla good"],
  },
  {
    id: 24,
    question: "How much calcium is in Spylt Milk?",
    answer: "Spylt Milk supplies calcium through its dairy base, supporting bone health and muscle function. Exact calcium content varies by flavor, so refer to the package label for precise values.",
    tags: ["calcium", "minerals", "nutrients", "spylt"],
    aliases: ["calcium in spylt", "how much calcium", "calcium content", "milk calcium"],
  },
  {
    id: 25,
    question: "Does Spylt Milk need refrigeration?",
    answer: "Yes, Spylt Milk should be refrigerated to stay fresh and safe. Keep it cold before and after opening, and follow the package storage instructions.",
    tags: ["refrigeration", "storage", "cold", "spylt"],
    aliases: ["needs refrigeration", "keep cold", "store cold", "refrigerate spylt"],
  },
  {
    id: 26,
    question: "Is Spylt Milk suitable for gym users?",
    answer: "Yes, Spylt Milk is tailored for gym users with protein, carbs, and nutrients that support workouts and recovery. It’s a convenient milk-based recovery drink.",
    tags: ["gym", "workout", "fitness", "spylt"],
    aliases: ["gym drink", "gym users", "fit milk", "workout milk"],
  },
  {
    id: 27,
    question: "What are the nutrition facts of Strawberry Spylt Milk?",
    answer: "Strawberry Spylt Milk offers protein, calories, carbs, sugars, and vitamins in a fruity dairy blend. Exact values depend on the product version, but it’s designed to support both taste and nutrition.",
    tags: ["strawberry", "nutrition facts", "spylt"],
    aliases: ["strawberry nutrition", "strawberry spylt facts", "strawberry milk facts", "nutrition strawberry"],
  },
  {
    id: 28,
    question: "Does Spylt Milk contain protein isolate?",
    answer: "Spylt Milk includes milk protein blends to deliver a strong protein profile. Some versions may use whey or casein protein sources rather than isolated protein powders.",
    tags: ["protein isolate", "protein blend", "ingredients", "spylt"],
    aliases: ["protein isolate spylt", "contains isolate", "protein type", "isolate in milk"],
  },
  {
    id: 29,
    question: "Is Cookies & Cream Spylt Milk high in calories?",
    answer: "Cookies & Cream Spylt Milk is slightly higher in calories due to its rich flavor profile, but it still fits well as a recovery drink or snack. It’s a bold option for those who want taste plus nutrition.",
    tags: ["cookies & cream", "calories", "flavor", "spylt"],
    aliases: ["cookies and cream calories", "high calorie spylt", "cookies cream milk", "calories cookies"],
  },
  {
    id: 30,
    question: "Can Spylt Milk replace a protein shake?",
    answer: "Spylt Milk can replace a protein shake for many users because it provides dairy protein, vitamins, and a tasty texture. It’s especially good when you want a more natural milk-based option.",
    tags: ["protein shake", "replacement", "recovery", "spylt"],
    aliases: ["replace protein shake", "instead of shake", "shake replacement", "protein drink"],
  },
  {
    id: 31,
    question: "Which Spylt Milk is best for weight gain?",
    answer: "Max Chocolate is often best for weight gain because it delivers higher protein and calorie content with a satisfying flavor. It’s a strong choice for recovery and muscle building.",
    tags: ["weight gain", "calories", "max chocolate", "spylt"],
    aliases: ["best for weight gain", "weight gain milk", "gain muscle spylt", "calorie dense"],
  },
  {
    id: 32,
    question: "Which Spylt Milk is best for weight loss?",
    answer: "For weight loss, choose a lower calorie Spylt option with high protein and less sugar, like Vanilla Cream or a lower-sugar version. It delivers nutrition without extra calories.",
    tags: ["weight loss", "low calorie", "vanilla", "spylt"],
    aliases: ["best for weight loss", "lose weight spylt", "diet milk", "low calorie spylt"],
  },
  {
    id: 33,
    question: "Is Spylt Peanut Butter Chocolate Milk healthy?",
    answer: "Yes, Peanut Butter Chocolate Spylt Milk is a healthy treat when used wisely. It offers protein, rich flavor, and satisfying energy, though it can be slightly richer than simpler varieties.",
    tags: ["peanut butter chocolate", "healthy", "flavor", "spylt"],
    aliases: ["peanut butter milk healthy", "pb choc spylt", "peanut butter chocolate calories", "health peanut butter"],
  },
  {
    id: 34,
    question: "Does Spylt Milk contain preservatives?",
    answer: "Spylt Milk is formulated with minimal preservatives and prioritizes fresh dairy ingredients. The product is designed for refrigerated storage and quality rather than shelf-stable additives.",
    tags: ["preservatives", "ingredients", "clean label", "spylt"],
    aliases: ["contains preservatives", "preserve spylt", "preservative count", "preservatives in milk"],
  },
  {
    id: 35,
    question: "Can diabetics drink Spylt Milk?",
    answer: "Diabetics can drink Spylt Milk if they choose lower-sugar options and monitor carbohydrate intake. It provides protein and calcium, but it should be part of a balanced meal plan.",
    tags: ["diabetics", "sugar", "health", "spylt"],
    aliases: ["diabetic milk", "diabetes spylt", "sugar diabetic", "diabetic safe"],
  },
  {
    id: 36,
    question: "Is Spylt Milk gluten free?",
    answer: "Most Spylt Milk products are gluten free because they are based on dairy and not grain ingredients. Always check the label for specific flavor formulations.",
    tags: ["gluten free", "allergy", "diet", "spylt"],
    aliases: ["gluten free spylt", "no gluten", "gluten in spylt", "is spylt gluten free"],
  },
  {
    id: 37,
    question: "What makes Spylt Milk different from other milk brands?",
    answer: "Spylt Milk stands out because it blends real dairy with extra protein, vitamins, and premium flavors. It’s designed to feel like milk while delivering fitness-focused nutrition.",
    tags: ["difference", "compare", "brand", "spylt"],
    aliases: ["different from other milk", "why spylt is different", "spylt vs other milk", "what makes spylt special"],
  },
  {
    id: 38,
    question: "How much carbs are in Spylt Milk?",
    answer: "Spylt Milk contains a moderate amount of carbs, often between 20–28g depending on the flavor. Carbs come from milk sugars and flavor ingredients, so check the label for exact details.",
    tags: ["carbs", "macros", "nutrition", "spylt"],
    aliases: ["carbs in spylt", "carb count", "carbohydrates spylt", "how many carbs"],
  },
  {
    id: 39,
    question: "Is Spylt Milk safe for teenagers?",
    answer: "Yes, Spylt Milk is safe for teenagers and provides protein, calcium, and dairy nutrition. It’s a good option for active teens as long as it fits their overall diet.",
    tags: ["teenagers", "teens", "safe", "spylt"],
    aliases: ["safe for teens", "teen milk", "spylt for teenagers", "kid teen safe"],
  },
  {
    id: 40,
    question: "Does Spylt Milk contain added protein?",
    answer: "Yes, Spylt Milk contains added dairy protein to boost each serving. It’s formulated with extra protein for recovery and muscle support.",
    tags: ["added protein", "protein boost", "spylt", "ingredients"],
    aliases: ["added protein spylt", "extra protein", "protein added", "protein content"],
  },
  {
    id: 41,
    question: "What is the healthiest Spylt flavor?",
    answer: "The healthiest Spylt flavor is usually the one with the lowest sugar and balanced macros, such as Vanilla Cream or a low-sugar variant. Choose what matches your goals.",
    tags: ["healthiest", "best for health", "flavor", "spylt"],
    aliases: ["healthiest flavor", "best healthy flavor", "healthy spylt flavor", "which flavor healthy"],
  },
  {
    id: 42,
    question: "Can Spylt Milk be used as breakfast?",
    answer: "Yes, Spylt Milk makes a convenient breakfast option because it delivers protein, dairy, and energy in one bottle. Pair it with fruit or oats for a complete morning meal.",
    tags: ["breakfast", "morning", "meal", "spylt"],
    aliases: ["breakfast milk", "morning drink", "breakfast spylt", "milk for breakfast"],
  },
  {
    id: 43,
    question: "Does Spylt Milk contain vitamins D and B12?",
    answer: "Yes, Spylt Milk is enriched with essential vitamins like D and B12 to support bone health and energy metabolism. This is part of its dairy nutrition profile.",
    tags: ["vitamin d", "b12", "vitamins", "spylt"],
    aliases: ["contains d and b12", "vitamin d spylt", "b12 spylt", "d and b12 in milk"],
  },
  {
    id: 44,
    question: "Is Max Chocolate Spylt Milk stronger in protein?",
    answer: "Yes, Max Chocolate is the strongest protein option in the Spylt lineup. It is crafted for serious recovery and muscle support with a bold chocolate profile.",
    tags: ["max chocolate", "stronger protein", "protein", "spylt"],
    aliases: ["max chocolate protein", "strong protein flavor", "more protein max chocolate", "stronger protein"],
  },
  {
    id: 45,
    question: "Can athletes drink Spylt Milk daily?",
    answer: "Yes, athletes can drink Spylt Milk daily to support recovery, protein needs, and hydration. It’s best when combined with whole foods and a balanced training plan.",
    tags: ["athletes", "daily", "sports", "spylt"],
    aliases: ["athlete daily milk", "daily athlete spylt", "sports drink", "athlete recovery"],
  },
  {
    id: 46,
    question: "Does Spylt Milk help recovery after exercise?",
    answer: "Yes, Spylt Milk helps recovery thanks to its protein, carbs, and dairy nutrients. It’s ideal after exercise for refueling and muscle support.",
    tags: ["recovery", "exercise", "workout", "spylt"],
    aliases: ["after exercise recovery", "post workout spylt", "recovery drink", "exercise recovery"],
  },
  {
    id: 47,
    question: "Is Spylt Milk sweet or low sugar?",
    answer: "Spylt Milk offers both sweet and lower-sugar options. Most flavors are pleasantly sweet, while some formulas focus on lower sugar for a lighter nutrition profile.",
    tags: ["sweet", "low sugar", "taste", "spylt"],
    aliases: ["sweet or low sugar", "sweet spylt", "low sugar spylt", "is spylt sweet"],
  },
  {
    id: 48,
    question: "Which Spylt Milk flavor is most popular?",
    answer: "Max Chocolate is the most popular Spylt flavor, followed closely by Vanilla Cream. They are praised for strong flavor and consistent nutrition.",
    tags: ["popular", "best seller", "flavor", "spylt"],
    aliases: ["most popular flavor", "favorite spylt", "top spylt flavor", "bestseller"],
  },
  {
    id: 49,
    question: "What are the benefits of drinking milk daily?",
    answer: "Drinking milk daily supports bone strength, protein intake, hydration, and recovery. Milk also supplies calcium, vitamins, and high-quality dairy nutrients.",
    tags: ["benefits", "daily milk", "milk benefits", "nutrition"],
    aliases: ["benefits of milk", "milk daily benefits", "daily dairy benefits", "why drink milk"],
  },
  {
    id: 50,
    question: "Is Spylt Milk good for energy and recovery?",
    answer: "Absolutely. Spylt Milk is designed for both energy and recovery, providing balanced carbs, protein, and vitamins to support active routines and fast recovery.",
    tags: ["energy", "recovery", "active", "spylt"],
    aliases: ["energy and recovery", "good for energy", "recovery drink spylt", "energy spylt"],
  },
];

export default faqDatabase;
